create table if not exists country_code_exception_address_model(
bank_identifier_key Integer not null,
country_code varchar(255) null,
branch_info varchar(255) null,
street_address1 varchar(255) null,
street_address2 varchar(255) null,
street_address3 varchar(255) null,
street_address4 varchar(255) null,
street_address5 varchar(255) null,
city varchar(255) null,
state varchar(255) null,
land_mark varchar(255) null,
zip_code varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint country_code_exception_address_model_pk primary key(bank_identifier_key));